### ISSUE TITLE
 error in opcode C_DUNGEON_COOL_TIME_LIST

### ISSUE THREAD

**Issue by motuson** [Tera-Shiraneko/fast-solo-dungeons#1]
error in opcode C_DUNGEON_COOL_TIME_LIST

**Comment by Tera-Shiraneko** [comment]
You need to map it yourself if its not mapped manually.

**Comment by lubask157** [comment]
how to fix this error?

**Comment by lubask157** [comment]
C_DUNGEON_COOL_TIME_LIST
