### ISSUE TITLE
LK teleport happens in full version, not just solo

### ISSUE THREAD

**Issue by Glyd** [Tera-Shiraneko/fast-solo-dungeons#1]
Crashes you sometimes too. If the dungeon codes are the same, maybe just a check for number of party members > 1? 

Thanks for this by the way, GG tp is brilliant.

**Comment by Tera-Shiraneko** [comment]
Yeah will add an check to prevent this even tho it's strange they use same map id's. Tje crash can happen sometimes if you are moving too fast after teleport or pulling aggro right after teleport.

**Comment by Tera-Shiraneko** [comment]
Issue has been fixed. Tested everything and it's working now. Thanks for the report.
