### ISSUE TITLE
Server keeps kicking me after I kill the first boss in Ace Lilith

### ISSUE THREAD

**Issue by Potatoreaper** [Tera-Shiraneko/fast-solo-dungeons#2]
This problem always occurs with archer, berserker and lancer
It also occasionally happens in other classes as well.

**Comment by Tera-Shiraneko** [comment]
It has nothing todo with the class and it can happen anytime you are teleporting far distances in a short amount of time. Even though I doesn't get kicked once I only get resynced back from time to time.

**Comment by Tera-Shiraneko** [comment]
On which region are you playing and are you still casting skills after the boss is dead?
