### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by brnbrito** [Tera-Shiraneko/fast-solo-dungeons#4]
Mod seems to work fine, though proxy reports this:

[dispatch] handle: error running hook for S_LOAD_TOPO<3>
hook: (anonymous) in fast solo dungeons
data: { zone: 7004,
  loc: Vec3 { x: 51694.61328125, y: 69409.6484375, z: 502 },
  quick: false }
error: [dispatch] write: failed to generate C_DUNGEON_COOL_TIME_LIST<1>:
Error: [protocol] write ("C_DUNGEON_COOL_TIME_LIST"): invalid code "null"'
    at Object.Solodungeon.mod.hook.event [as callback] (C:\Users\Bruno\Desktop\tera-proxy\mods\fast-solo-dungeons-master\index.js:16:13)

Is that anything we should worry about?

**Comment by Tera-Shiraneko** [comment]
Nothing to worry about you just need the opcode and definition to make it work without errors. Cause this is an unethical module they are not mapped/added by default.
